// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using OrderFsm.Models;
using System;

namespace OrderFsm.Migrations
{
    [DbContext(typeof(OrderContext))]
    partial class OrderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OrderFsm.OrderProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Assignee");

                    b.Property<bool>("IsComplete");

                    b.Property<bool>("IsOrderCheckSucess");

                    b.Property<string>("Key");

                    b.Property<bool>("ManualSuccess");

                    b.Property<bool>("PricingSuccess");

                    b.Property<string>("State");

                    b.HasKey("Id");

                    b.ToTable("OrderProcesses");
                });
#pragma warning restore 612, 618
        }
    }
}
